name = "Turtledove Mod Pack"
author = "eristocrates"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dcd4592a704b87322ffd0611f7333749ca2be1e0e0e87a3f88633ceaed50ceb1"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
no-internal-hashes = true
