name = "Turtledove Mod Pack"
author = "eristocrates"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5731a5be9ca8707c9ec826a231885ecaf0df4df7253462a3793fa0ffb16af44"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"

[options]
no-internal-hashes = true
